project_name:
  type: str
  help: What is the name of your project?
  default: my-chainlit-app

description:
  type: str
  help: Short description of the project
  default: A Chainlit Chat Application

openai_api_key:
  type: str
  help: What is your Albert API Key? (Get one at https://albert.sites.beta.gouv.fr/access/)

openai_base_url:
  type: str
  help: What is your OpenAI Base URL?
  default: https://albert.api.etalab.gouv.fr/v1

openai_model:
  type: str
  help: Default OpenAI model to use
  default: openweight-large

system_prompt:
  type: str
  help: Initial system prompt for the assistant
  default: You are a helpful assistant.

welcome_message:
  type: str
  help: Header text for the welcome screen
  default: Welcome to Chainlit! ðŸš€ðŸ¤–
